version: "3"

services:
  injestor:
    build: .
    ports:
      - 80:8080
    volumes:
      - images:/static/images
    environment:
      - SPRING_PROFILES_ACTIVE=injestor
    depends_on:
      - postgres
      - queue
  queue:
    image: rabbitmq:3.9-management
    ports:
      - 15672:15672
    volumes:
      - queuev:/var/lib/rabbitmq
  worker:
    build: .
    volumes:  
      - images:/static/images
    environment:
      - SPRING_PROFILES_ACTIVE=worker
    depends_on:
      - postgres
      - queue
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: imrec
    volumes:
      - dbv-imrec:/var/lib/postgresql/data
volumes:
  images: {}
  dbv-imrec: {}
  queuev: {}